name: Coverage

on:
  push:
    branches:
    - '*'
    paths:
    - '**.rkt'
    - '**.scrbl'
  pull_request:
    branches:
    - '*'
    paths:
    - '**.rkt'
    - '**.scrbl'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Racket
        uses: Bogdanp/setup-racket@v1.3.1
        with:
          architecture: 'x64'
          distribution: 'minimal'
          variant: 'CS'
          version: '8.1'
          packages: 'cover, cover-coveralls, cover-codecov'
      - run: raco pkg install --auto --batch
      - run: |
          make test
          raco cover -b -n dev -f coveralls .
