name: Coverage

on:
  push:
    branches:
    - '*'
    paths:
    - '**.rkt'
  pull_request:
    branches:
    - '*'
    paths:
    - '**.rkt'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cover:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Cache installed packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.racket
        key: ${{ runner.os }}-primes
    - name: Setup Racket
      uses: Bogdanp/setup-racket@v1.2.1
      with:
        architecture: 'x64' # (x64 or x86), ignored on Linux
        distribution: 'minimal'
        variant: 'CS'
        version: '8.0'
        packages: 'cover, cover-codecov'
    - run: raco pkg install --auto
    - run: raco cover -f codecov .
