name: Coverage

on:
  push:
    branches:
    - '*'
    paths:
    - '**.rkt'
    - '**.scrbl'
  pull_request:
    branches:
    - '*'
    paths:
    - '**.rkt'
    - '**.scrbl'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Cache installed packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.racket
        key: ${{ runner.os }}-primes
    - name: Setup Racket
      uses: Bogdanp/setup-racket@v1.1
      with:
        architecture: 'x64' # (x64 or x86), ignored on Linux
        variant: 'CS'
        version: 8.0
        packages: 'cover'
    - run: raco pkg install --auto
    - run: raco cover -f coveralls .
