# This is a basic workflow to help you get started with Actions
name: Publish

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [develop]
    paths:
      - "**publish.yml"
      - "**.scrbl"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Cache installed packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/racket
            ~/.local/share/racket
          key: ${{ runner.os }}-racket
      - uses: Bogdanp/setup-racket@v1.7
        with:
          architecture: x64
          distribution: full
          variant: "CS"
          version: "stable"
      - name: Build
        run: |
          raco pkg install --auto --skip-installed
          raco scribble --htmls ++main-xref-in --redirect-main http://docs.racket-lang.org/ --dest doc scribblings/${{ github.event.repository.name }}.scrbl
      - name: Deploy Document
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/${{ github.event.repository.name }}
          publish_branch: master
